<?php
/**
 * Country Code helper
 * - convert codes between FIPS 10-4 and ISO 3166-1 notation
 *
 * @package DatingVIP
 * @subpackage geo
 * @author Boris Momcilovic <boris@firstbeatmedia.com>
 * @copyright &copy; 2014 firstbeatmedia.com
 * @version 1.0
 */

namespace DatingVIP\geo;

class Country_Code
{

/**
 * Map of FIPS 10-4 to ISO 3166-1 country codes
 *
 * @var array $fips2iso
 * @access protected
 * @see http://opengeocode.org/download/fips2iso.txt
 */
    protected $fips2iso =
    [
        'AF' => 'AF',
        'AL' => 'AL',
        'AG' => 'DZ',
        'AQ' => 'AS',
        'AN' => 'AD',
        'AO' => 'AO',
        'AV' => 'AI',
        'AY' => 'AQ',
        'AC' => 'AG',
        'AR' => 'AR',
        'AM' => 'AM',
        'AA' => 'AW',
        'AS' => 'AU',
        'AU' => 'AT',
        'AJ' => 'AZ',
        'BF' => 'BS',
        'BA' => 'BH',
        'BG' => 'BD',
        'BB' => 'BB',
        'BO' => 'BY',
        'BE' => 'BE',
        'BH' => 'BZ',
        'BN' => 'BJ',
        'BD' => 'BM',
        'BT' => 'BT',
        'BL' => 'BO',
        'BK' => 'BA',
        'BC' => 'BW',
        'BV' => 'BV',
        'BR' => 'BR',
        'IO' => 'IO',
        'VI' => 'VG',
        'BX' => 'BN',
        'BU' => 'BG',
        'UV' => 'BF',
        'BM' => 'MM',
        'BY' => 'BI',
        'CB' => 'KH',
        'CM' => 'CM',
        'CA' => 'CA',
        'CV' => 'CV',
        'CJ' => 'KY',
        'CT' => 'CF',
        'CD' => 'TD',
        'CI' => 'CL',
        'CH' => 'CN',
        'KT' => 'CX',
        'CK' => 'CC',
        'CO' => 'CO',
        'CN' => 'KM',
        'CG' => 'CD',
        'CF' => 'CG',
        'CW' => 'CK',
        'CS' => 'CR',
        'IV' => 'CI',
        'HR' => 'HR',
        'CU' => 'CU',
        'UC' => 'CW',
        'CY' => 'CY',
        'EZ' => 'CZ',
        'DA' => 'DK',
        'DJ' => 'DJ',
        'DO' => 'DM',
        'DR' => 'DO',
        'EC' => 'EC',
        'EG' => 'EG',
        'ES' => 'SV',
        'EK' => 'GQ',
        'ER' => 'ER',
        'EN' => 'EE',
        'ET' => 'ET',
        'FK' => 'FK',
        'FO' => 'FO',
        'FJ' => 'FJ',
        'FI' => 'FI',
        'FR' => 'FR',
        'FG' => 'GF',
        'FP' => 'PF',
        'FS' => 'TF',
        'GB' => 'GA',
        'GA' => 'GM',
        'GG' => 'GE',
        'GM' => 'DE',
        'GH' => 'GH',
        'GI' => 'GI',
        'GR' => 'GR',
        'GL' => 'GL',
        'GJ' => 'GD',
        'GP' => 'GP',
        'GQ' => 'GU',
        'GT' => 'GT',
        'GK' => 'GG',
        'GV' => 'GN',
        'PU' => 'GW',
        'GY' => 'GY',
        'HA' => 'HT',
        'HM' => 'HM',
        'VT' => 'VA',
        'HO' => 'HN',
        'HK' => 'HK',
        'HU' => 'HU',
        'IC' => 'IS',
        'IN' => 'IN',
        'ID' => 'ID',
        'IR' => 'IR',
        'IZ' => 'IQ',
        'EI' => 'IE',
        'IM' => 'IM',
        'IS' => 'IL',
        'IT' => 'IT',
        'JM' => 'JM',
        'JA' => 'JP',
        'JE' => 'JE',
        'JO' => 'JO',
        'KZ' => 'KZ',
        'KE' => 'KE',
        'KR' => 'KI',
        'KN' => 'KP',
        'KS' => 'KR',
        'KU' => 'KW',
        'KG' => 'KG',
        'LA' => 'LA',
        'LG' => 'LV',
        'LE' => 'LB',
        'LT' => 'LS',
        'LI' => 'LR',
        'LY' => 'LY',
        'LS' => 'LI',
        'LH' => 'LT',
        'LU' => 'LU',
        'MC' => 'MO',
        'MK' => 'MK',
        'MA' => 'MG',
        'MI' => 'MW',
        'MY' => 'MY',
        'MV' => 'MV',
        'ML' => 'ML',
        'MT' => 'MT',
        'RM' => 'MH',
        'MB' => 'MQ',
        'MR' => 'MR',
        'MP' => 'MU',
        'MF' => 'YT',
        'MX' => 'MX',
        'FM' => 'FM',
        'MD' => 'MD',
        'MN' => 'MC',
        'MG' => 'MN',
        'MJ' => 'ME',
        'MH' => 'MS',
        'MO' => 'MA',
        'MZ' => 'MZ',
        'WA' => 'NA',
        'NR' => 'NR',
        'NP' => 'NP',
        'NL' => 'NL',
        'NC' => 'NC',
        'NZ' => 'NZ',
        'NU' => 'NI',
        'NG' => 'NE',
        'NI' => 'NG',
        'NE' => 'NU',
        'NF' => 'NF',
        'CQ' => 'MP',
        'NO' => 'NO',
        'MU' => 'OM',
        'PK' => 'PK',
        'PS' => 'PW',
        'PM' => 'PA',
        'PP' => 'PG',
        'PA' => 'PY',
        'PE' => 'PE',
        'RP' => 'PH',
        'PC' => 'PN',
        'PL' => 'PL',
        'PO' => 'PT',
        'RQ' => 'PR',
        'QA' => 'QA',
        'RE' => 'RE',
        'RO' => 'RO',
        'RS' => 'RU',
        'RW' => 'RW',
        'TB' => 'BL',
        'SH' => 'SH',
        'SC' => 'KN',
        'ST' => 'LC',
        'RN' => 'MF',
        'SB' => 'PM',
        'VC' => 'VC',
        'WS' => 'WS',
        'SM' => 'SM',
        'TP' => 'ST',
        'SA' => 'SA',
        'SG' => 'SN',
        'RI' => 'RS',
        'SE' => 'SC',
        'SL' => 'SL',
        'SN' => 'SG',
        'NN' => 'SX',
        'LO' => 'SK',
        'SI' => 'SI',
        'BP' => 'SB',
        'SO' => 'SO',
        'SF' => 'ZA',
        'SX' => 'GS',
        'SP' => 'ES',
        'CE' => 'LK',
        'SU' => 'SD',
        'NS' => 'SR',
        'SV' => 'SJ',
        'WZ' => 'SZ',
        'SW' => 'SE',
        'SZ' => 'CH',
        'SY' => 'SY',
        'TW' => 'TW',
        'TI' => 'TJ',
        'TZ' => 'TZ',
        'TH' => 'TH',
        'TT' => 'TL',
        'TO' => 'TG',
        'TL' => 'TK',
        'TN' => 'TO',
        'TD' => 'TT',
        'TS' => 'TN',
        'TU' => 'TR',
        'TX' => 'TM',
        'TK' => 'TC',
        'TV' => 'TV',
        'UG' => 'UG',
        'UP' => 'UA',
        'AE' => 'AE',
        'UK' => 'GB',
        'US' => 'US',
        'UY' => 'UY',
        'UZ' => 'UZ',
        'NH' => 'VU',
        'VE' => 'VE',
        'VM' => 'VN',
        'VQ' => 'VI',
        'WF' => 'WF',
        'WI' => 'EH',
        'YM' => 'YE',
        'ZA' => 'ZM',
        'ZI' => 'ZW',
    ];

/**
 * FIPS 2 ISO
 *
 * @param string $code
 * @access public
 * @return string
 */
    public function fips2iso($code)
    {
        $code    = strtoupper ((string) $code);
        return array_key_exists ($code, $this->fips2iso) ? $this->fips2iso[$code] : '';
    }

/**
 * ISO 2 FIPS
 *
 * @param string $code
 * @access public
 * @return string
 */
    public function iso2fips($code)
    {
        $code   = strtoupper ((string) $code);
        $map    = array_flip ($this->fips2iso);
        return array_key_exists ($code, $map) ? $map[$code] : '';
    }

}
